### ISSUE TITLE
CM-App GUI support for Long Lived Tokens

### ISSUE THREAD

**Issue by kthare10** [fabric-testbed/CredentialManager#54]
* CM needs the following changes to create tokens:
    * User should be able to specify the lifetime of the token with default set to 4 hour and pull down menu 1 week; 2 week upto 9 weeks
        * CM-App should translate the lifetime into hours before invoking the Rest API
    * CM would allow user to cut-paste the token to be installed in their software
* For tracking validity
    * Add new List Tokens:  
        * List all currently active tokens using the API: https://alpha-2.fabric-testbed.net/credmgr/ui/#/tokens/tokens_get
    * Add new menu to Validate a Token: 
        * CM should allow the user to submit their token for verification via e.g. a form and say ‘valid’ or ‘expired’ or ‘revoked’ or ‘invalid’
        * API to use: https://alpha-2.fabric-testbed.net/credmgr/ui/#/tokens/tokens_validate_post
* For revocation
    * Revoke Section of the CM-App should let the user specify:
        * Type of the token: Identity or Refresh
        * Token: Would be token hash in case of Identify Token and Refresh Token in case of Refresh Token
        * New API should be used: https://alpha-2.fabric-testbed.net/credmgr/ui/#/tokens/tokens_revoke_post

Revised requirements:

- [x] Remove Refresh Token and Revoke Refresh Token from GUI;

- [x] Combined the Select Project component for Create Token and List Tokens into one dropdown on the top;

- [x] When user logs in, CM-App invokes GET /whoami API to get user’s uuid and then lists projects;

- Michael updated Core API: the `memberships` portion of `/projects/{uuid}` and `/projects?person_uuid=xxx` contain an `is_token_holder` attribute;
- When a user selects a project under create token; CM-app can check if the `is_token_holder` is present in the `memberships`;
If present; allow users to change lifetime with units hours, days, weeks (may be add a helper text/small banner to indicate this is long lived token)
- Otherwise; lifetime should be set to 4 hours and greyed out
- The message box above the form options should also be conditionally rendered:  "You have access to [long-lived tokens](https://learn.fabric-testbed.net/knowledge-base/obtaining-and-using-fabric-api-tokens/#creating-long-lived-api-tokens) for this project. The lifetime limit is 9 weeks." or "The default token lifetime is 4 hours. You don't have access to [long-lived tokens](https://learn.fabric-testbed.net/knowledge-base/obtaining-and-using-fabric-api-tokens/#creating-long-lived-api-tokens) for this project."

- [x] List and Validate Tokens can stay the same

**Comment by yaxue1123** [comment]
**Create Token**

- [ ] default lifetime is 4 hours and user can also use the drop-down select to choose 1-9 weeks' long lived token option (app should convert the time to hours before passing to CM API);
- [ ] Add a `comment` input field for users to give the token a name/ comment since there maybe multiple tokens to differentiate with;
- [ ] Response is updated with more fields as below. 

```
 "data": [
    {
      "comment": "string",
      "created_at": "string",
      "created_from": "string",
      "expires_at": "string",
      "id_token": "string",
      "refresh_token": "string",
      "state": "Nascent",
      "token_hash": "string"
    }
  ]
```

**Refresh Token**

- [ ] Refresh-token feature basically stays the same. But regular tokens have `refresh_token` while long lived tokens don't. 

**Revoke Token**

- [ ] Use updated endpoint POST `tokens/revokes`;
- [ ] Request body should be formatted as below. For regular tokens, use `refresh_token` as `token`, "refresh" as `type`; For long lived tokens, use `token_hash` as `token` and "identity" as `type`.
```
{
  "token": "string",
  "type": "identity"
}
```

**[NEW] List Tokens**

- [ ] Could be a new page to list all currently active tokens.

**[NEW] Validate Token**

- [ ]  User can submit a token for verification to check if the token is ‘valid’ or ‘expired’ or ‘revoked’ or ‘invalid’.
